### PR TITLE
Ensure all objects have consistent resolution orders.

### PR DESCRIPTION
**Pull request by janjaapdriessen**

### CODE REVIEW

**Comment by janjaapdriessen** [comment]
Thank you for your reviews Marius and Jason, I'll wait for the zope.interface work to land before making any more changes. There is a tear-your-hair-out IRO warning in the grok package that I hope will (magically) go away as a result of the changes in zope.interface. I have made branches of zc.catalog and zope.testbrowser, other than those and grok/grokcore.rest I didn't find any packages that need IRO changes. 
If the time comes, I will be most happy to help fix travis config files etc. 

https://github.com/zopefoundation/zc.catalog/tree/consistent-iro
https://github.com/zopefoundation/zope.testbrowser/pull/93/files

**Comment by icemac** [comment]
What is the current status of this PR? Is there something to be done before it can be merged?

**Comment by jamadden** [comment]
Because https://github.com/zopefoundation/zope.interface/pull/203 was merged, this PR probably only needs to add the environment variable to tox.ini and .travis.yml; the code change is probably not necessary.

**Comment by icemac** [comment]
Thank you for the PR and reviewing it. 😃

**Pull request merged**
